### ISSUE TITLE
Library file names are wrong for Mac OS X

### ISSUE THREAD

**Issue by rgobbel** [cordawyn/redlander#2]
In redland.rb there are hardcoded strings for "rdf.so.0" and "librdf.so.0". For Mac OS X these should be "rdf.0" and "librdf.0".

Here's the error that currently pops up:

1.9.3-p374 :001 > require 'redland'
LoadError: Could not open library 'rdf.so.0': dlopen(rdf.so.0, 5): image not found.
Could not open library 'librdf.so.0.dylib': dlopen(librdf.so.0.dylib, 5): image not found
    from /Users/gobbel/.rvm/gems/ruby-1.9.3-p374/gems/ffi-1.3.1/lib/ffi/library.rb:123:in `block in ffi_lib'

**Comment by cordawyn** [comment]
Hi @gobbel. Thanks for the bug report!

I don't have Mac OS X to test it, but could you edit `lib/redland.rb` and replace the whole "if ... else ... end" block in line 5 with:

```
require "ffi"
extend FFI::Library
ffi_lib "rdf"
```

and see if it works for you?

**Comment by rgobbel** [comment]
I get this:

bash-3.2$ irb
irb
1.9.3-p374 :001 > require 'redlander'
require 'redlander'
NameError: uninitialized constant Redland::FFI
 from
/Users/gobbel/.rvm/gems/ruby-1.9.3-p374/gems/redlander-0.5.2/lib/redland.rb:4:in
`<module:Redland>'
from
/Users/gobbel/.rvm/gems/ruby-1.9.3-p374/gems/redlander-0.5.2/lib/redland.rb:3:in
`<top (required)>'
 from
/Users/gobbel/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in
`require'
from
/Users/gobbel/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in
`require'
 from
/Users/gobbel/.rvm/gems/ruby-1.9.3-p374/gems/redlander-0.5.2/lib/redlander.rb:3:in
`<top (required)>'
from
/Users/gobbel/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in
`require'
 from
/Users/gobbel/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in
`rescue in require'
from
/Users/gobbel/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in
`require'
 from (irb):1
from /Users/gobbel/.rvm/rubies/ruby-1.9.3-p374/bin/irb:16:in `<main>'
1.9.3-p374 :002 >

On Fri, Feb 15, 2013 at 12:12 PM, Slava Kravchenko <notifications@github.com

**Comment by cordawyn** [comment]
You probably forgot to add `require "ffi"`.

**Comment by rgobbel** [comment]
Sure enough, that works. -Randy

**Comment by cordawyn** [comment]
I've pushed the update to the repository, will release a newer gem version a bit later.
Thanks for the help!
