### ISSUE TITLE
Efficient iteration of statements from librdf streams

### ISSUE THREAD

**Issue by abargnesi** [cordawyn/redlander#6]
Recently I have used ruby redland-bindings to iterate statements without creating many ruby objects. The iterator could be configured with options to only return a certain part of the S, P, O triple which reduced the number of librdf library calls. This iteration decreased the wall-clock time by about 4 times IIRC and kept memory allocation low.

The approach can be seen in [this gist](https://gist.github.com/abargnesi/7764981817f6ad411279).

I would love to have this approach as an option in redlander, because the FFI implementation works across all ruby engines.

Is this of value to redlander?

**Comment by cordawyn** [comment]
Sounds like a very good idea. However, I think we could do even better with redlander. Let me concoct a nice little pull request implementing my take on this and we'll discuss it in a short while. I'll update this issue when it's ready.

**Comment by cordawyn** [comment]
On a related note, is it a common practice to create lazy enumerators by calling `enum_for(:each).lazy`? Judging by the output of `inspect`, it produces "an enumerator within another enumerator". Compare the output, for example:

```
[1,2,3].enum_for => #<Enumerator: [1, 2, 3]:each>
[1,2,3].lazy => #<Enumerator::Lazy: [1, 2, 3]:each>
[1,2,3].enum_for.lazy => #<Enumerator::Lazy: #<Enumerator: [1, 2, 3]:each>>
[1,2,3].lazy.enum_for => #<Enumerator::Lazy: #<Enumerator::Lazy: [1, 2, 3]>:each>
```

I have little to none experience working directly with lazy enumerators in Ruby, perhaps you could clarify this nuance for me? I think that the 2nd output is what one should expect.

**Comment by abargnesi** [comment]
I believe you are correct regarding `Enumerable#lazy`. If `lazy` is available then return a new `Enumerator::Lazy` otherwise return a new `Enumerator`.

Maybe the pattern is then something like:

``` ruby
def each
  if block_given?
    # yield elements to block
  else
    if respond_to? :lazy
      lazy
    else
      to_enum
    end
  end
end
```

**Comment by cordawyn** [comment]
Except that `lazy` is defined only for `Array`s and `Enumerator`s. I was hoping it would be a part of `Enumerable` module, but it appears that it isn't. :-(
So far, I ended with the following "pattern" in place of "lazy" in your last example:

```
Enumerator::Lazy.new(self) {|yielder, n| yielder.yield(n) }
```

It works in limited cases though. It won't work with a customized `each` which requires arguments because there's no way to pass those arguments. There _is_ `Enumerator::Lazy.enum_for` method, but it defines the enumerator for `Enumerator::Lazy` itself. Ugh.

I'm still investigating.

**Comment by abargnesi** [comment]
I am seeing lazy defined for Enumerable in pry (`show-doc Enumerable#lazy`). Here it is on ruby-doc too: http://ruby-doc.org/core-2.0/Enumerable.html#method-i-lazy

What am I missing?

**Comment by cordawyn** [comment]
I must have missed it. Thanks for noticing! However, it still won't allow to pass the arguments to `each` that is called internally. Perhaps, I'll have to end up with my own implementation of `lazy` for redlander.

**Comment by abargnesi** [comment]
Can you create the initial `Enumerator` with `enum_for(*args)` and then call lazy if available? This would match my original solution. Here is a contrived example:

``` ruby
class LetterRange
  include Enumerable

  def initialize(start_value = 'a', end_value = 'zzzzzz')
    @start_value = start_value
    @end_value = end_value
  end

  def each(*args)
    if block_given?
      matches = args.flatten
      if matches.empty?
        (@start_value..@end_value).each do |value|
          yield value
        end
      else
        (@start_value..@end_value).each do |value|
          yield value if matches.include?(value)
        end
      end
    else
      enumerator = enum_for(:each, *args)
      respond_to?(:lazy) ? enumerator.lazy : enumerator
    end
  end
end

words = %w[the brown fox lazy dog]
LetterRange.new('a', 'zzzzzzzzzzz').
  each(words).
  take(words.size).
  each do |value|
    puts value
  end
```

**Comment by abargnesi** [comment]
The additional `Enumerator` doesn't add much. Here is a quick wall-clock time comparison:

``` ruby
require 'benchmark'

puts (0..10_000_000).enum_for.map.inspect
puts Benchmark.measure {
  (0..10_000_000).enum_for.map { |x| x * 2 }.select { |x| x.even? }
}
```

``` bash
#<Enumerator: #<Enumerator: 0..10000000:each>:map>
  5.070000   0.020000   5.090000 (  5.103417)
```

``` ruby
require 'benchmark'

puts (0..10_000_000).map.inspect
puts Benchmark.measure {
  (0..10_000_000).map { |x| x * 2 }.select { |x| x.even? }
}
```

``` bash
#<Enumerator: 0..10000000:map>
  5.040000   0.010000   5.050000 (  5.059363)
```

**Comment by cordawyn** [comment]
Btw, since `ModelProxy` (of redlander) has `Enumerable` included, it has `lazy` already. So, you can try:

```
model.statements.lazy.each {...}
```

and it should just work (C).
I don't want to implement laziness as it is implemented in your example because this is not a default behaviour of standard Ruby `each` - it is recommended to use `.lazy.each` combo. So, as long as this is expected standard behaviour, I'd rather it stays as it is now. Please try whether my above suggestion works for you.
There are still a few additional tweaks that I have made as mentioned earlier. I'll send them for review later today.

**Comment by cordawyn** [comment]
Presumably, additional enumerators should not add much, as you've noticed - after all, these "chained" enumerators just pull the values one-by-one from the chain. It's not that one enumerator (even non-lazy) has to pull all of the values before a subsequent enumerator pulls just a single value from the output. I'm more concerned with extra objects on the stack and some additional work for GC. Not a big deal for small examples, but who knows how big it can grow for large projects. Besides, the philosophy of redlander is to be "lightweight", so I'd like to take extra pain to ensure that ;-)
Anyway, I hope the problem should be solved "automagically" as I've mentioned in the previous example. Please let me know how it works for you.

**Comment by cordawyn** [comment]
@abargnesi Here you go: https://github.com/cordawyn/redlander/pull/8

**Comment by cordawyn** [comment]
I guess, we're done with this one. If not, feel free to reopen the issue.
