### ISSUE TITLE
creating Redlander::Node for a ruby string representing URI

### ISSUE THREAD

**Issue by abargnesi** [cordawyn/redlander#9]
The Redlander::Node `rdf_node` pointer cannot be created from a string URI. The following conversion is needed:
- construct ruby string for URI
- call `Kernel#URI` to convert to `URI` object
- call `Redlander::Node.new` with `URI` object

Using `Kernel#URI` is slow and adds unnecessary overhead given you ultimately call `Redland.librdf_new_node_from_uri_string(Redlander.rdf_world, @arg.to_s)`.

Should we add an option to treat string as resource URI and not a literal?

**Comment by cordawyn** [comment]
That makes sense.

Would this work for you?

```
Node.new("http://example.org/", :resource => true)
```

or you'd rather prefer

```
Node.as_resource("http://example.org/")
(or make it #new_resource or #make_resource?)
```

I can do both, but somehow the former sounds more consistent with the current design, because we already have _options_ hash in Node.new (with the only option `blank_id` there).

**Comment by cordawyn** [comment]
Anyway, here it is: 3cb65af35208cd51ce25f714cfc99effa2c60282

**Comment by abargnesi** [comment]
I like your choice of `resource`. It is describing what the argument is and not what the argument does. The latter is up to the implementation of `Node`.

It worked great for my needs. Thanks.
